//#region src/patch.ts
/** Prefix each patch row carries so an importer can find its own rows. */
const SWITCHBLADE_ROW = "switchblade";
const AGENT_PRESETS_ROW = "agent-presets";
/**
* Render the current Switchblade state as a `cordis.patch.yml` bundle layer.
* @param patch - state to persist into the patch.
* @returns YAML text ready to drop into a profile bundle's `cordis.patch.yml`.
*/
function renderPatch(patch) {
	const lines = ["# Generated by @deepseek-ai/dsh-switchblade export — re-instates the", "# managed skills, custom commands, and default profile on this profile."];
	lines.push("", "- insert:");
	lines.push(...renderRow(SWITCHBLADE_ROW, "@deepseek-ai/dsh-switchblade", {
		installedSkills: patch.installedSkills.map((skill) => ({
			name: skill.name,
			content: skill.content,
			description: skill.description,
			invocation: skill.invocation
		})),
		customCommands: patch.customCommands.map((command) => ({
			name: command.name,
			description: command.description,
			handlerBehavior: "passthrough"
		}))
	}));
	if (patch.defaultProfile !== void 0) lines.push(...renderRow(AGENT_PRESETS_ROW, "@deepseek-ai/dsh-agent-presets", { default: patch.defaultProfile }));
	return `${lines.join("\n")}\n`;
}
/** Render one `- insert:` row as indented YAML lines. */
function renderRow(id, name, config) {
	const out = [
		`    - id: ${id}`,
		`      name: '${name}'`,
		"      config:"
	];
	out.push(...renderValue(config, 8));
	return out;
}
/** Render a JSON-compatible value as indented YAML. Arrays of objects emit `- key:` items. */
function renderValue(value, indent) {
	const pad = " ".repeat(indent);
	if (Array.isArray(value)) {
		const out = [];
		for (const entry of value) if (Array.isArray(entry) || typeof entry === "object" && entry !== null) out.push(...renderObject(entry, indent, true));
		else out.push(`${pad}- ${scalar(entry)}`);
		return out;
	}
	if (typeof value === "object" && value !== null) return renderObject(value, indent, false);
	return [`${pad}${scalar(value)}`];
}
/** Render an object; when `dash` is true the first key carries the `- ` list marker. */
function renderObject(obj, indent, dash) {
	const pad = " ".repeat(indent);
	const out = [];
	const entries = Object.entries(obj);
	for (let index = 0; index < entries.length; index += 1) {
		const entry = entries[index];
		if (entry === void 0) continue;
		const [key, val] = entry;
		const prefix = index === 0 && dash ? `${pad}- ` : pad;
		if (typeof val === "object" && val !== null) {
			out.push(`${prefix}${key}:`);
			out.push(...renderValue(val, indent + (index === 0 && dash ? 4 : 2)));
		} else out.push(`${prefix}${key}: ${scalar(val)}`);
	}
	return out;
}
/** Render a scalar leaf, quoting strings for YAML safety. */
function scalar(value) {
	if (typeof value === "string") return JSON.stringify(value);
	if (value === void 0) return "null";
	return String(value);
}
/**
* Best-effort parse of the rows this exporter writes. Rows it does not
* recognize are ignored, so an external patch may carry other plugins.
* @param text - a `cordis.patch.yml` document.
* @returns the switchblade-owned rows found in it.
*/
function parsePatch(text) {
	let installedSkills = [];
	let customCommands = [];
	let defaultProfile;
	const lines = text.split(/\r?\n/);
	let inInsert = false;
	let currentRow;
	let currentArray;
	let currentItem;
	let pendingItems = [];
	const flush = () => {
		if (currentItem !== void 0) pendingItems.push(currentItem);
		currentItem = void 0;
		if (currentArray === "installedSkills") installedSkills = pendingItems.map((item) => ({
			name: item.name ?? "",
			content: item.content ?? "",
			description: item.description ?? "",
			invocation: {
				modelInvocable: true,
				userInvocable: true
			},
			provider: "runtime",
			source: "custom"
		}));
		else if (currentArray === "customCommands") customCommands = pendingItems.map((item) => ({
			name: item.name ?? "",
			description: item.description ?? "",
			handler: () => ({
				kind: "success",
				text: ""
			})
		}));
		pendingItems = [];
	};
	for (const raw of lines) {
		const line = raw.trim();
		if (/^- insert:/.test(line)) {
			inInsert = true;
			continue;
		}
		if (!inInsert) continue;
		const idMatch = /^- id:\s*(.+)$/.exec(line);
		if (idMatch !== null) {
			flush();
			currentArray = void 0;
			currentRow = idMatch[1];
			continue;
		}
		if (currentRow === void 0) continue;
		if (line.startsWith("config:")) {
			flush();
			currentArray = void 0;
			const inline = /^config:\s*\{([^}]*)\}\s*$/.exec(raw.trim());
			if (inline !== null) {
				const body = inline[1] ?? "";
				const def = /default:\s*["']?([^"',}]+)["']?/.exec(body);
				if (def !== null) defaultProfile = def[1] ?? def[0];
			}
			continue;
		}
		if (currentRow === AGENT_PRESETS_ROW) {
			const def = /^default:\s*["']?([^"']+)["']?$/.exec(line);
			if (def !== null) defaultProfile = dequote(def[1] ?? "");
		}
		const arrayMatch = /^installedSkills:|^customCommands:/.exec(line);
		if (arrayMatch !== null) {
			flush();
			currentArray = arrayMatch[0].replace(":", "");
			continue;
		}
		if (currentArray !== void 0) {
			const itemStart = /^-\s+(\w+):\s*(.*)$/.exec(line);
			if (itemStart !== null) {
				flush();
				const key = itemStart[1];
				const rawValue = itemStart[2];
				if (key !== void 0 && rawValue !== void 0) currentItem = { [key]: dequote(rawValue) };
				continue;
			}
			const field = /^(\w+):\s*(.*)$/.exec(line);
			if (field !== null && currentItem !== void 0) {
				const key = field[1];
				const rawValue = field[2];
				if (key !== void 0 && rawValue !== void 0) {
					if (key === "name" || key === "content" || key === "description") currentItem[key] = dequote(rawValue);
				}
			}
		}
	}
	flush();
	return {
		installedSkills,
		customCommands,
		...defaultProfile === void 0 ? {} : { defaultProfile }
	};
}
/** Strip surrounding quotes from a scalar produced by this exporter. */
function dequote(raw) {
	const value = raw.trim();
	if (value.length >= 2 && value.startsWith("\"") && value.endsWith("\"")) return value.slice(1, -1).replaceAll("\\\"", "\"");
	if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) return value.slice(1, -1);
	return value;
}
//#endregion
export { parsePatch, renderPatch };
