import { Service } from "@deepseek-ai/cordis";
import { cp, mkdir, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { homedir } from "node:os";
import { basename, join } from "node:path";
import { settingsNamespace } from "@deepseek-ai/dsh-settings";
import z from "@deepseek-ai/schemastery";
//#region lib/types/invariant.js
/** Prefix used to namespaced-entry `id`s at the action seam. */
const ID_PREFIX = {
	skill: "skill",
	profile: "profile",
	command: "command"
};
/**
* Return whether a candidate install name is a safe runtime skill name.
* @param name - candidate skill name.
* @returns whether it satisfies the public skill-name grammar (kebab-case).
*/
function isInstallSkillName(name) {
	return /^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(name);
}
/**
* Return whether a kebab or underscore command name is a safe slash command.
* @param name - candidate command name without a leading slash.
* @returns whether it satisfies the command grammar.
*/
function isCommandName(name) {
	return /^[a-z][a-z0-9_-]*$/u.test(name);
}
//#endregion
//#region lib/types/patch.js
/**
* bundle patch-layer serialization for `@deepseek-ai/dsh-switchblade`.
*
* A DSH "bundle" is a package whose package.json declares `dsh.bundle.patch`
* pointing at a `cordis.patch.yml`. Profile composition resolves that field and
* overlays the patch rows onto the profile root; later patches win per row id.
* This module renders and re-parses the subset of that format Switchblade owns:
* the `switchblade` row (carrying the installed skill + custom command rows as
* plugin config) and the `agent-presets` default row.
*
* The serializer is deliberately small and dependency-free. It emits the same
* block-style YAML shape the harness bundles use (`- id:` rows with nested
* arrays), and `parsePatch` understands exactly that shape for the rows this
* exporter writes. Swap in a real YAML parser for arbitrary external bundles.
*
* @module @deepseek-ai/dsh-switchblade/patch
*/
/** Prefix each patch row carries so an importer can find its own rows. */
const SWITCHBLADE_ROW = "switchblade";
const AGENT_PRESETS_ROW = "agent-presets";
/**
* Render the current Switchblade state as a `cordis.patch.yml` bundle layer.
* @param patch - state to persist into the patch.
* @returns YAML text ready to drop into a profile bundle's `cordis.patch.yml`.
*/
function renderPatch(patch) {
	const lines = ["# Generated by @deepseek-ai/dsh-switchblade export — re-instates the", "# managed skills, custom commands, and default profile on this profile."];
	lines.push("", "- insert:");
	lines.push(...renderRow(SWITCHBLADE_ROW, "@deepseek-ai/dsh-switchblade", {
		installedSkills: patch.installedSkills.map((skill) => ({
			name: skill.name,
			content: skill.content,
			description: skill.description,
			invocation: skill.invocation
		})),
		customCommands: patch.customCommands.map((command) => ({
			name: command.name,
			description: command.description,
			handlerBehavior: "passthrough"
		}))
	}));
	if (patch.defaultProfile !== void 0) lines.push(...renderRow(AGENT_PRESETS_ROW, "@deepseek-ai/dsh-agent-presets", { default: patch.defaultProfile }));
	return `${lines.join("\n")}\n`;
}
/** Render one `- insert:` row as indented YAML lines. */
function renderRow(id, name, config) {
	const out = [
		`    - id: ${id}`,
		`      name: '${name}'`,
		"      config:"
	];
	out.push(...renderValue(config, 8));
	return out;
}
/** Render a JSON-compatible value as indented YAML. Arrays of objects emit `- key:` items. */
function renderValue(value, indent) {
	const pad = " ".repeat(indent);
	if (Array.isArray(value)) {
		const out = [];
		for (const entry of value) if (Array.isArray(entry) || typeof entry === "object" && entry !== null) out.push(...renderObject(entry, indent, true));
		else out.push(`${pad}- ${scalar(entry)}`);
		return out;
	}
	if (typeof value === "object" && value !== null) return renderObject(value, indent, false);
	return [`${pad}${scalar(value)}`];
}
/** Render an object; when `dash` is true the first key carries the `- ` list marker. */
function renderObject(obj, indent, dash) {
	const pad = " ".repeat(indent);
	const out = [];
	const entries = Object.entries(obj);
	for (let index = 0; index < entries.length; index += 1) {
		const entry = entries[index];
		if (entry === void 0) continue;
		const [key, val] = entry;
		const prefix = index === 0 && dash ? `${pad}- ` : pad;
		if (typeof val === "object" && val !== null) {
			out.push(`${prefix}${key}:`);
			out.push(...renderValue(val, indent + (index === 0 && dash ? 4 : 2)));
		} else out.push(`${prefix}${key}: ${scalar(val)}`);
	}
	return out;
}
/** Render a scalar leaf, quoting strings for YAML safety. */
function scalar(value) {
	if (typeof value === "string") return JSON.stringify(value);
	if (value === void 0) return "null";
	return String(value);
}
/**
* Best-effort parse of the rows this exporter writes. Rows it does not
* recognize are ignored, so an external patch may carry other plugins.
* @param text - a `cordis.patch.yml` document.
* @returns the switchblade-owned rows found in it.
*/
function parsePatch(text) {
	let installedSkills = [];
	let customCommands = [];
	let defaultProfile;
	const lines = text.split(/\r?\n/);
	let inInsert = false;
	let currentRow;
	let currentArray;
	let currentItem;
	let pendingItems = [];
	const flush = () => {
		if (currentItem !== void 0) pendingItems.push(currentItem);
		currentItem = void 0;
		if (currentArray === "installedSkills") installedSkills = pendingItems.map((item) => ({
			name: item.name ?? "",
			content: item.content ?? "",
			description: item.description ?? "",
			invocation: {
				modelInvocable: true,
				userInvocable: true
			},
			provider: "runtime",
			source: "custom"
		}));
		else if (currentArray === "customCommands") customCommands = pendingItems.map((item) => ({
			name: item.name ?? "",
			description: item.description ?? "",
			handler: () => ({
				kind: "success",
				text: ""
			})
		}));
		pendingItems = [];
	};
	for (const raw of lines) {
		const line = raw.trim();
		if (/^- insert:/.test(line)) {
			inInsert = true;
			continue;
		}
		if (!inInsert) continue;
		const idMatch = /^- id:\s*(.+)$/.exec(line);
		if (idMatch !== null) {
			flush();
			currentArray = void 0;
			currentRow = idMatch[1];
			continue;
		}
		if (currentRow === void 0) continue;
		if (line.startsWith("config:")) {
			flush();
			currentArray = void 0;
			const inline = /^config:\s*\{([^}]*)\}\s*$/.exec(raw.trim());
			if (inline !== null) {
				const body = inline[1] ?? "";
				const def = /default:\s*["']?([^"',}]+)["']?/.exec(body);
				if (def !== null) defaultProfile = def[1] ?? def[0];
			}
			continue;
		}
		if (currentRow === AGENT_PRESETS_ROW) {
			const def = /^default:\s*["']?([^"']+)["']?$/.exec(line);
			if (def !== null) defaultProfile = dequote(def[1] ?? "");
		}
		const arrayMatch = /^installedSkills:|^customCommands:/.exec(line);
		if (arrayMatch !== null) {
			flush();
			currentArray = arrayMatch[0].replace(":", "");
			continue;
		}
		if (currentArray !== void 0) {
			const itemStart = /^-\s+(\w+):\s*(.*)$/.exec(line);
			if (itemStart !== null) {
				flush();
				const key = itemStart[1];
				const rawValue = itemStart[2];
				if (key !== void 0 && rawValue !== void 0) currentItem = { [key]: dequote(rawValue) };
				continue;
			}
			const field = /^(\w+):\s*(.*)$/.exec(line);
			if (field !== null && currentItem !== void 0) {
				const key = field[1];
				const rawValue = field[2];
				if (key !== void 0 && rawValue !== void 0) {
					if (key === "name" || key === "content" || key === "description") currentItem[key] = dequote(rawValue);
				}
			}
		}
	}
	flush();
	return {
		installedSkills,
		customCommands,
		...defaultProfile === void 0 ? {} : { defaultProfile }
	};
}
/** Strip surrounding quotes from a scalar produced by this exporter. */
function dequote(raw) {
	const value = raw.trim();
	if (value.length >= 2 && value.startsWith("\"") && value.endsWith("\"")) return value.slice(1, -1).replaceAll("\\\"", "\"");
	if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) return value.slice(1, -1);
	return value;
}
//#endregion
//#region lib/types/switchblade.js
/**
* `Switchblade` — the Host-side core of the management surface.
*
* One service reasons about the three CCswitch-style targets through the real
* DSH seams:
*
*  - `ctx.skill` — owner skills are registered as *runtime* skills via
*    `ctx.skills.register()` (each returns a disposer = uninstall), and
*    provider-discovered skills are listed for visibility.
*  - `ctx.agentPresets` — prompt profiles map onto the preset roster
*    (`copy`/`remove`), and the session default lives in the `agent-presets`
*    settings namespace.
*  - `ctx.commands` — custom slash commands register via `ctx.commands.register()`.
*
* State persists through a `switchblade` settings namespace. Public methods are
* `@Remote` so the Web UI projection calls the same Host service over the
* generated Typert RPC.
*
* @module @deepseek-ai/dsh-switchblade
*/
/** Promise-wrapped execFile for the zip extraction helper. */
const execFileAsync = promisify(execFile);
/** Switchblade settings namespace name. */
const SETTINGS_NAMESPACE = "switchblade";
/** Runtime schema for the persisted slice. */
const SwitchbladeSettingsSchema = z.object({
	installedSkills: z.array(z.any()).default([]),
	customCommands: z.array(z.any()).default([]),
	prompts: z.array(z.any()).default([])
});
/** One prompt section id prefix registered on ctx.systemPrompt. */
const PROMPT_SECTION_PREFIX = "switchblade:prompt:";
/**
* Registry over skills, prompt profiles, and slash commands.
*
* Lifecycle model matches CCswitch: an initialized object is "installed", then
* flipped between "enabled" (registered/visible) and "disabled" (registration
* disposed). Only owned skills — those installed from a local source — change
* the registry; provider-discovered skills are treated as read-only inventory.
*/
var Switchblade = class extends Service {
	config;
	/** Services the plugin reads from ctx; inject-declared so Cordis resolves them. */
	static inject = [
		"loader",
		"skills",
		"systemPrompt"
	];
	/** Registry configuration. */
	static Config = z.object({ defaultProfile: z.string() });
	/** Live enabled registration disposers, keyed by entry id. */
	registrations = /* @__PURE__ */ new Map();
	/** Live disposers for enabled prompt sections, keyed by prompt id. */
	promptSections = /* @__PURE__ */ new Map();
	/** The settings namespace scope; present only while a settings provider is composed. */
	settingsScope;
	/** The settings service behind {@link settingsScope}, for path writes. */
	settingsService;
	constructor(ctx, config = {}) {
		super(ctx, "switchblade");
		this.config = config;
		ctx.logger.warn("[switchblade] Switchblade service constructed");
		ctx.inject(["settings"], (settingsCtx) => {
			const scope = settingsCtx.settings.register(settingsNamespace(SETTINGS_NAMESPACE), SwitchbladeSettingsSchema, { base: {} });
			this.settingsScope = scope;
			this.settingsService = settingsCtx.settings;
			let reconciling = false;
			let scheduled = false;
			const reconcile = () => {
				if (scheduled) return;
				scheduled = true;
				queueMicrotask(() => {
					scheduled = false;
					if (reconciling) return;
					reconciling = true;
					try {
						this.applyPromptRegistrations();
					} catch (e) {
						settingsCtx.logger.warn(`[switchblade] prompt reconcile: ${String(e)}`);
					}
					try {
						this.applySkillRegistrations();
					} catch (e) {
						settingsCtx.logger.warn(`[switchblade] skill reconcile: ${String(e)}`);
					}
					reconciling = false;
				});
			};
			scope.watch(reconcile);
			settingsCtx.effect(() => () => {
				this.settingsScope = void 0;
				this.settingsService = void 0;
			}, "switchblade.settings()");
			settingsCtx.logger.warn(`[switchblade] settings registered; prompts=${scope.get().prompts.length} skills=${scope.get().installedSkills.length}`);
			this.reinstall(scope.get());
		});
	}
	/** All persisted state, merged over schema defaults. */
	settings() {
		return this.settingsScope?.get() ?? {
			installedSkills: [],
			customCommands: [],
			prompts: []
		};
	}
	/** All managed prompts, sorted (default first, then by order). */
	listPrompts() {
		return [...this.settings().prompts].sort((a, b) => Number(b.isDefault) - Number(a.isDefault) || a.order - b.order);
	}
	/**
	* Add a new prompt. Persists it, marks it enabled, and injects it into the
	* system prompt (global scope — every agent reads it).
	* @param input - name, description, and content.
	* @returns the created prompt.
	*/
	async addPrompt(input) {
		const name = input.name.trim();
		if (name.length === 0) throw new Error("prompt name is required");
		if (input.content.trim().length === 0) throw new Error("prompt content is required");
		const id = this.slugify(name);
		const prompts = this.settings().prompts;
		if (prompts.some((p) => p.id === id)) throw new Error(`a prompt named "${name}" already exists`);
		const prompt = {
			id,
			name,
			description: input.description.trim(),
			content: input.content,
			order: prompts.length,
			enabled: true,
			isDefault: prompts.length === 0
		};
		await this.writePrompts([...prompts, prompt]);
		this.applyPromptRegistrations();
		return prompt;
	}
	/** Toggle one prompt's global injection. */
	async setPromptEnabled(id, enabled) {
		const next = this.settings().prompts.map((p) => p.id === id ? {
			...p,
			enabled
		} : p);
		await this.writePrompts(next);
		this.applyPromptRegistrations();
	}
	/** Mark one prompt as the default (sorted first); clears the others. */
	async setDefaultPrompt(id) {
		const next = this.settings().prompts.map((p) => ({
			...p,
			isDefault: p.id === id
		}));
		await this.writePrompts(next);
	}
	/** Update a prompt's name/description/content. */
	async updatePrompt(id, patch) {
		const next = this.settings().prompts.map((p) => {
			if (p.id !== id) return p;
			return {
				...p,
				name: patch.name?.trim() || p.name,
				description: patch.description?.trim() ?? p.description,
				content: patch.content ?? p.content
			};
		});
		await this.writePrompts(next);
		this.applyPromptRegistrations();
	}
	/** Delete one prompt and un-inject it. */
	async deletePrompt(id) {
		const next = this.settings().prompts.filter((p) => p.id !== id);
		await this.writePrompts(next);
		this.applyPromptRegistrations();
	}
	/** Persist the prompt list. */
	async writePrompts(prompts) {
		await this.settingsService?.mutate(settingsNamespace(SETTINGS_NAMESPACE), [{
			op: "set",
			path: ["prompts"],
			value: prompts
		}]);
	}
	/**
	* Reconcile live systemPrompt registrations against the persisted prompt
	* list. Directly reads this.ctx.systemPrompt (the plugin's own context can
	* resolve it; no ctx.inject here — that would spawn a fiber inside the
	* settings watch callback and deadlock the commit path). Fully guarded so a
	* bad prompt never wedges settings.
	*/
	applyPromptRegistrations() {
		try {
			const system = this.ctx.systemPrompt;
			if (system === void 0 || typeof system.section !== "function") {
				this.ctx.logger.warn("[switchblade] systemPrompt service unavailable — prompts will NOT be injected");
				return;
			}
			this.ctx.logger.warn(`[switchblade] applying prompt registrations: ${this.listPrompts().filter((p) => p.enabled).length} enabled`);
			const wanted = /* @__PURE__ */ new Set();
			for (const prompt of this.listPrompts()) {
				if (!prompt.enabled) continue;
				wanted.add(prompt.id);
				const key = `${PROMPT_SECTION_PREFIX}${prompt.id}`;
				if (!this.promptSections.has(prompt.id)) try {
					const dispose = system.section({
						name: key,
						order: 200 + prompt.order,
						text: prompt.content
					});
					this.promptSections.set(prompt.id, dispose);
					this.ctx.logger.warn(`[switchblade] registered prompt section ${key} (order ${200 + prompt.order})`);
				} catch (error) {
					this.ctx.logger.warn(`[switchblade] failed to register prompt ${prompt.name}: ${String(error)}`);
				}
			}
			for (const [id, dispose] of [...this.promptSections]) if (!wanted.has(id)) {
				dispose();
				this.promptSections.delete(id);
			}
		} catch (error) {
			this.ctx.logger.warn(`[switchblade] prompt reconcile failed: ${String(error)}`);
		}
	}
	/** Live disposers for enabled prompt sections, keyed by prompt id. */
	/**
	* Reconcile live runtime-skill registrations against the persisted
	* installedSkills list (honoring each skill's `enabled` flag). Called on
	* startup and whenever the settings namespace changes.
	*/
	applySkillRegistrations() {
		try {
			const skills = this.ctx.skills;
			if (skills === void 0 || typeof skills.register !== "function") return;
			const wanted = /* @__PURE__ */ new Set();
			for (const def of this.settings().installedSkills) {
				const id = `${ID_PREFIX.skill}:${def.name}`;
				if (!(def.enabled ?? true)) continue;
				wanted.add(id);
				if (!this.registrations.has(id)) try {
					this.registrations.set(id, skills.register(def));
				} catch (error) {
					this.ctx.logger.warn(`[switchblade] failed to register skill ${def.name}: ${String(error)}`);
				}
			}
			for (const [id, dispose] of [...this.registrations]) if (!wanted.has(id)) {
				dispose();
				this.registrations.delete(id);
			}
		} catch (error) {
			this.ctx.logger.warn(`[switchblade] skill reconcile failed: ${String(error)}`);
		}
	}
	/** Sluggify a display name into a stable id. */
	slugify(value) {
		const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
		return slug.length > 0 ? slug : `prompt-${Date.now()}`;
	}
	/**
	* The full management catalog.
	* @param agent - agent whose command view to read; omitted, the command
	*   section is empty (the CLI handler supplies it).
	* @returns normalized entries and the defaulted profile id.
	*/
	async catalog(agent) {
		const raw = await this.snapshot(agent);
		const entries = [
			...raw.skills.map((skill) => this.ownedSkillEntry(skill)),
			...raw.presets.map((preset) => this.profileEntry(preset)),
			...raw.commands.map((descriptor) => this.commandEntry(descriptor))
		];
		const defaultProfile = this.config.defaultProfile ?? await this.currentProfile();
		return {
			entries,
			...defaultProfile === void 0 ? {} : { defaultProfile }
		};
	}
	/**
	* Install an owned skill from a local source and enable it immediately.
	* @param input - skill name, body, and routing metadata.
	* @returns the addressed id and resulting state.
	*/
	async installSkill(input) {
		if (!isInstallSkillName(input.name)) throw new TypeError(`skill name "${input.name}" must be kebab-case`);
		const id = `${ID_PREFIX.skill}:${input.name}`;
		if (this.registrations.get(id) !== void 0) return {
			id,
			state: "enabled"
		};
		const definition = {
			name: input.name,
			content: input.content,
			description: input.description,
			invocation: input.invocation ?? {
				modelInvocable: true,
				userInvocable: true
			},
			provider: input.provider ?? "runtime",
			source: "custom"
		};
		return {
			id,
			state: await this.setOwnedSkill(id, definition, true)
		};
	}
	/**
	* Install a skill from a local directory (SKILL.md + references, or a flat
	* .md) by copying it into the user skills root (`~/.dsh/skills`), which the
	* official `skill-filesystem` provider scans. This makes directory skills
	* (multi-file, with references) fully loadable and invocable via `/name`.
	* @param sourceDir - absolute path of the skill directory (or .md file).
	* @returns the installed skill name.
	*/
	async installSkillFromDir(sourceDir) {
		const root = join(homedir(), ".dsh", "skills");
		await mkdir(root, { recursive: true });
		const name = basename(sourceDir).replace(/\.md$/i, "");
		const target = join(root, name);
		await cp(sourceDir, target, {
			recursive: true,
			force: true
		});
		this.ctx.logger.warn(`[switchblade] installed skill from dir ${sourceDir} → ${target}`);
		try {
			const { readFile } = await import("node:fs/promises");
			const md = await readFile(join(sourceDir, "SKILL.md"), "utf8").catch(() => void 0) ?? await readFile(sourceDir, "utf8").catch(() => void 0);
			if (md !== void 0) {
				const skillName = parseSkillName(md) ?? name;
				const desc = parseSkillDescription(md) ?? "";
				await this.registerManagedSkill(skillName, desc, md);
			}
		} catch (error) {
			this.ctx.logger.warn(`[switchblade] failed to register dir skill ${name}: ${String(error)}`);
		}
		return name;
	}
	/** Write a flat skill .md into the user skills root. */
	async installSkillFile(name, content) {
		const root = join(homedir(), ".dsh", "skills");
		await mkdir(root, { recursive: true });
		const target = join(root, `${name}.md`);
		await writeFile(target, content, "utf8");
		this.ctx.logger.warn(`[switchblade] wrote skill file ${target}`);
		return name;
	}
	/**
	* Register a skill into the managed installedSkills list (persisted) and as
	* a runtime registration, so it appears in the panel's Skills tab and is
	* callable via /name.
	*/
	async registerManagedSkill(name, description, content) {
		const definition = {
			name,
			content,
			description,
			invocation: {
				modelInvocable: true,
				userInvocable: true
			},
			provider: "runtime",
			source: "custom"
		};
		const id = `${ID_PREFIX.skill}:${name}`;
		const existing = this.registrations.get(id);
		if (existing !== void 0) {
			existing();
			this.registrations.delete(id);
		}
		try {
			this.registrations.set(id, this.ctx.skills.register(definition));
		} catch (error) {
			this.ctx.logger.warn(`[switchblade] runtime register of ${name} failed: ${String(error)}`);
		}
		const current = this.settings().installedSkills;
		if (!current.some((s) => s.name === name)) {
			await this.settingsService?.mutate(settingsNamespace(SETTINGS_NAMESPACE), [{
				op: "set",
				path: ["installedSkills"],
				value: [...current, definition]
			}]);
			this.ctx.logger.warn(`[switchblade] registered managed skill ${name}`);
		}
	}
	/**
	* Install skills from a zip archive by extracting it into the user skills
	* root (`~/.dsh/skills`). Uses the platform archive tool (tar on Windows
	* 10+ handles zip; macOS/Linux tar handles zip) — zero extra dependencies.
	* The zip may contain one skill (SKILL.md at root) or many skill dirs.
	* @param zipPath - absolute path to the .zip archive.
	* @returns the extracted directory names.
	*/
	async installSkillFromZip(zipPath) {
		const root = join(homedir(), ".dsh", "skills");
		await mkdir(root, { recursive: true });
		const temp = join(root, `.zip-tmp-${Date.now()}`);
		await mkdir(temp, { recursive: true });
		try {
			await execFileAsync("tar", [
				"-xf",
				zipPath,
				"-C",
				temp
			]);
		} catch {
			await execFileAsync("powershell", [
				"-NoProfile",
				"-Command",
				`Expand-Archive -LiteralPath '${zipPath}' -DestinationPath '${temp}' -Force`
			]);
		}
		const { readdir, readFile } = await import("node:fs/promises");
		const entries = await readdir(temp);
		const installed = [];
		for (const entry of entries) {
			const src = join(temp, entry);
			const target = join(root, entry);
			await cp(src, target, {
				recursive: true,
				force: true
			});
			installed.push(entry);
			this.ctx.logger.warn(`[switchblade] installed zip entry ${entry} → ${target}`);
			try {
				const md = await readFile(join(target, "SKILL.md"), "utf8").catch(() => void 0);
				if (md !== void 0) {
					const name = parseSkillName(md) ?? entry;
					const desc = parseSkillDescription(md) ?? "";
					await this.registerManagedSkill(name, desc, md);
				} else {
					const flat = await readFile(src, "utf8").catch(() => void 0);
					if (flat !== void 0) {
						const name = parseSkillName(flat) ?? entry.replace(/\.md$/i, "");
						const desc = parseSkillDescription(flat) ?? "";
						await this.registerManagedSkill(name, desc, flat);
					}
				}
			} catch (error) {
				this.ctx.logger.warn(`[switchblade] failed to register zip entry ${entry} as managed: ${String(error)}`);
			}
		}
		await execFileAsync(process.platform === "win32" ? "rmdir" : "rm", process.platform === "win32" ? [
			"/s",
			"/q",
			temp
		] : ["-rf", temp]);
		return installed;
	}
	/**
	* Uninstall an owned skill, disposing its runtime registration.
	* @param name - runtime skill name to remove.
	* @returns the addressed id and resulting state.
	*/
	async uninstallSkill(name) {
		const id = `${ID_PREFIX.skill}:${name}`;
		await this.setOwnedSkill(id, void 0, false);
		return {
			id,
			state: "disabled"
		};
	}
	/** Toggle one owned skill's runtime registration on or off. */
	async setSkillEnabled(name, enabled) {
		const id = `${ID_PREFIX.skill}:${name}`;
		return {
			id,
			state: await this.setOwnedSkillEnabled(id, enabled)
		};
	}
	/** List all skill summary rows, regardless of ownership. */
	async listSkills() {
		return (await this.ctx.skills.list({})).map((skill) => ({
			id: `${ID_PREFIX.skill}:${skill.name}`,
			name: skill.name,
			description: skill.description
		}));
	}
	/** Copy a shipped preset into a locally authored prompt profile. */
	async addProfile(from, id, name) {
		await this.authorableRoster().copy(from, id, name);
	}
	/** Remove a locally authored prompt profile. */
	async removeProfile(id) {
		await this.agentPresetsOrThrow().remove(id);
	}
	/** The prompt profile composed when a session names none. */
	async currentProfile() {
		return this.agentPresetsOrThrow().defaultId;
	}
	/** Persist a new session default prompt profile. */
	async setDefaultProfile(id) {
		const service = this.settingsService;
		if (service === void 0) return;
		await service.mutate(settingsNamespace("agent-presets"), [{
			op: "set",
			path: ["default"],
			value: id
		}]);
	}
	/** Register a custom slash command and persist it for reinstatement. */
	async registerCommand(definition) {
		if (!isCommandName(definition.name)) throw new TypeError(`command name "${definition.name}" must match the command grammar`);
		this.ctx.commands.register(definition);
		const next = this.settings().customCommands;
		if (!next.some((row) => row.name === definition.name)) await this.settingsService?.mutate(settingsNamespace(SETTINGS_NAMESPACE), [{
			op: "set",
			path: ["customCommands"],
			value: [...next, definition]
		}]);
	}
	/** Unregister a custom slash command. */
	async unregisterCommand(name) {
		const id = `${ID_PREFIX.command}:${name}`;
		this.registrations.get(id)?.();
		this.registrations.delete(id);
		const rest = this.settings().customCommands.filter((row) => row.name !== name);
		await this.settingsService?.mutate(settingsNamespace(SETTINGS_NAMESPACE), [{
			op: "set",
			path: ["customCommands"],
			value: rest
		}]);
	}
	/**
	* Export the current managed state as a bundle patch layer (`cordis.patch.yml`).
	* Drop the returned text into a profile bundle's patch file to re-instate the
	* same skills, custom commands, and default profile on another process.
	*/
	async exportBundle() {
		const settings = this.settings();
		const defaultProfile = this.config.defaultProfile;
		return renderPatch({
			installedSkills: settings.installedSkills,
			customCommands: settings.customCommands,
			...defaultProfile === void 0 ? {} : { defaultProfile }
		});
	}
	/**
	* Import switchblade-owned rows from a bundle patch and apply them. The
	* persisted slice is replaced, live registrations are rebuilt, and any
	* `agent-presets` default in the patch is adopted.
	* @param patch - a `cordis.patch.yml` document the exporter (or a compatible
	*   bundle) produced.
	*/
	async importBundle(patch) {
		const parsed = parsePatch(patch);
		for (const dispose of this.registrations.values()) dispose();
		this.registrations.clear();
		for (const definition of parsed.installedSkills) this.registrations.set(`${ID_PREFIX.skill}:${definition.name}`, this.ctx.skills.register(definition));
		for (const row of parsed.customCommands) this.registrations.set(`${ID_PREFIX.command}:${row.name}`, this.ctx.commands.register(passthroughCommand(row)));
		await this.settingsService?.mutate(settingsNamespace(SETTINGS_NAMESPACE), [{
			op: "set",
			path: ["installedSkills"],
			value: parsed.installedSkills
		}, {
			op: "set",
			path: ["customCommands"],
			value: parsed.customCommands
		}]);
		if (parsed.defaultProfile !== void 0) await this.setDefaultProfile(parsed.defaultProfile);
	}
	/** Build the raw snapshot underlying a catalog. */
	async snapshot(agent) {
		const [skills, presets] = await Promise.all([this.ctx.skills.list({}), this.agentPresetsOrThrow().list()]);
		return {
			skills,
			presets,
			commands: this.ctx.commands === void 0 ? [] : this.ctx.commands.list(agent)
		};
	}
	/** Re-register every persisted owned row after a settings reload. */
	reinstall(settings) {
		this.applySkillRegistrations();
		try {
			const commands = this.ctx.commands;
			if (commands !== void 0 && typeof commands.register === "function") for (const row of settings.customCommands) {
				const id = `${ID_PREFIX.command}:${row.name}`;
				if (!this.registrations.has(id)) this.registrations.set(id, commands.register(passthroughCommand(row)));
			}
		} catch (error) {
			this.ctx.logger.warn(`[switchblade] custom command reinstall failed: ${String(error)}`);
		}
		if (settings.prompts.length > 0) this.applyPromptRegistrations();
	}
	/** Flip one owned skill's runtime registration and persist the definition set. */
	async setOwnedSkill(id, def, enabled) {
		const existing = this.registrations.get(id);
		if (existing !== void 0) {
			existing();
			this.registrations.delete(id);
		}
		if (def !== void 0 && enabled) this.registrations.set(id, this.ctx.skills.register(def));
		const kept = this.settings().installedSkills.filter((row) => `${ID_PREFIX.skill}:${row.name}` !== id);
		const next = def === void 0 ? kept : [...kept, def];
		await this.settingsService?.mutate(settingsNamespace(SETTINGS_NAMESPACE), [{
			op: "set",
			path: ["installedSkills"],
			value: next
		}]);
		return enabled ? "enabled" : "disabled";
	}
	async setOwnedSkillEnabled(id, enabled) {
		const definition = this.settings().installedSkills.find((row) => `${ID_PREFIX.skill}:${row.name}` === id);
		if (definition === void 0) throw new Error(`owned skill "${id}" is not installed`);
		const existing = this.registrations.get(id);
		if (existing !== void 0) {
			existing();
			this.registrations.delete(id);
		}
		if (enabled) this.registrations.set(id, this.ctx.skills.register(definition));
		return enabled ? "enabled" : "disabled";
	}
	ownedSkillEntry(skill) {
		return {
			kind: "skill",
			id: `${ID_PREFIX.skill}:${skill.name}`,
			name: skill.name,
			description: skill.description,
			state: this.registrations.has(`${ID_PREFIX.skill}:${skill.name}`) ? "enabled" : "disabled",
			source: skill.source,
			invocation: skill.invocation,
			owned: this.registrations.has(`${ID_PREFIX.skill}:${skill.name}`)
		};
	}
	profileEntry(preset) {
		return {
			kind: "profile",
			id: `${ID_PREFIX.profile}:${preset.id}`,
			name: preset.name ?? preset.id,
			description: preset.description ?? "agent preset",
			state: "installed",
			isDefault: preset.id === this.config.defaultProfile,
			preset
		};
	}
	commandEntry(descriptor) {
		return {
			kind: "command",
			id: `${ID_PREFIX.command}:${descriptor.name}`,
			name: descriptor.name,
			description: descriptor.description,
			state: this.registrations.has(`${ID_PREFIX.command}:${descriptor.name}`) ? "enabled" : "installed",
			descriptor
		};
	}
	/** The agent-preset roster, read live from the composition. */
	agentPresetsOrThrow() {
		const service = this.ctx.get("agentPresets");
		if (service === void 0) throw new Error("switchblade requires the agent-presets service to manage prompt profiles");
		return service;
	}
	authorableRoster() {
		return this.agentPresetsOrThrow();
	}
};
/** Parse the frontmatter `name:` field from a skill markdown body. */
function parseSkillName(md) {
	return /^---[\s\S]*?^name:\s*([^\n]+)/m.exec(md)?.[1]?.trim();
}
/** Parse the frontmatter `description:` field from a skill markdown body. */
function parseSkillDescription(md) {
	return /^---[\s\S]*?^description:\s*([^\n]+)/m.exec(md)?.[1]?.trim();
}
/** Starter handler for imported command rows that arrive without a real handler. */
function passthroughCommand(row) {
	if (typeof row.handler === "function") return row;
	return {
		...row,
		handler: async () => ({
			kind: "success",
			text: row.description
		})
	};
}
//#endregion
export { SETTINGS_NAMESPACE, Switchblade, Switchblade as default, SwitchbladeSettingsSchema };
