/**
 * bundle patch-layer serialization for `@deepseek-ai/dsh-switchblade`.
 *
 * A DSH "bundle" is a package whose package.json declares `dsh.bundle.patch`
 * pointing at a `cordis.patch.yml`. Profile composition resolves that field and
 * overlays the patch rows onto the profile root; later patches win per row id.
 * This module renders and re-parses the subset of that format Switchblade owns:
 * the `switchblade` row (carrying the installed skill + custom command rows as
 * plugin config) and the `agent-presets` default row.
 *
 * The serializer is deliberately small and dependency-free. It emits the same
 * block-style YAML shape the harness bundles use (`- id:` rows with nested
 * arrays), and `parsePatch` understands exactly that shape for the rows this
 * exporter writes. Swap in a real YAML parser for arbitrary external bundles.
 *
 * @module @deepseek-ai/dsh-switchblade/patch
 */

import type { CommandDefinition } from '@deepseek-ai/dsh-commands'
import type { SkillDefinition } from '@deepseek-ai/dsh-skill'

/** The patch rows Switchblade owns on export. */
export interface SwitchbladePatch {
  /** Owned skills reinstated on the target profile. */
  readonly installedSkills: readonly SkillDefinition[]
  /** Custom slash commands reinstated on the target profile. */
  readonly customCommands: readonly CommandDefinition[]
  /** Profile id to default, or undefined when none was pinned. */
  readonly defaultProfile?: string
}

/** Prefix each patch row carries so an importer can find its own rows. */
const SWITCHBLADE_ROW = 'switchblade'
const AGENT_PRESETS_ROW = 'agent-presets'

/**
 * Render the current Switchblade state as a `cordis.patch.yml` bundle layer.
 * @param patch - state to persist into the patch.
 * @returns YAML text ready to drop into a profile bundle's `cordis.patch.yml`.
 */
export function renderPatch(patch: SwitchbladePatch): string {
  const lines: string[] = [
    '# Generated by @deepseek-ai/dsh-switchblade export — re-instates the',
    '# managed skills, custom commands, and default profile on this profile.',
  ]
  lines.push('', '- insert:')
  lines.push(...renderRow(SWITCHBLADE_ROW, '@deepseek-ai/dsh-switchblade', {
    installedSkills: patch.installedSkills.map((skill) => ({
      name: skill.name,
      content: skill.content,
      description: skill.description,
      invocation: skill.invocation,
    })),
    customCommands: patch.customCommands.map((command) => ({
      name: command.name,
      description: command.description,
      handlerBehavior: 'passthrough', // signal to the importer; the CLI handler is starter glue
    })),
  }))
  if (patch.defaultProfile !== undefined) {
    lines.push(...renderRow(AGENT_PRESETS_ROW, '@deepseek-ai/dsh-agent-presets', {
      default: patch.defaultProfile,
    }))
  }
  return `${lines.join('\n')}\n`
}

/** Render one `- insert:` row as indented YAML lines. */
function renderRow(id: string, name: string, config: object): string[] {
  const out: string[] = [`    - id: ${id}`, `      name: '${name}'`, '      config:']
  out.push(...renderValue(config, 8))
  return out
}

/** Render a JSON-compatible value as indented YAML. Arrays of objects emit `- key:` items. */
function renderValue(value: unknown, indent: number): string[] {
  const pad = ' '.repeat(indent)
  if (Array.isArray(value)) {
    const out: string[] = []
    for (const entry of value) {
      if (Array.isArray(entry) || (typeof entry === 'object' && entry !== null)) {
        out.push(...renderObject(entry as Record<string, unknown>, indent, true))
      } else {
        out.push(`${pad}- ${scalar(entry)}`)
      }
    }
    return out
  }
  if (typeof value === 'object' && value !== null) {
    return renderObject(value as Record<string, unknown>, indent, false)
  }
  return [`${pad}${scalar(value)}`]
}

/** Render an object; when `dash` is true the first key carries the `- ` list marker. */
function renderObject(obj: Record<string, unknown>, indent: number, dash: boolean): string[] {
  const pad = ' '.repeat(indent)
  const out: string[] = []
  const entries = Object.entries(obj)
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index]
    if (entry === undefined) continue
    const [key, val] = entry
    const prefix = index === 0 && dash ? `${pad}- ` : pad
    if (typeof val === 'object' && val !== null) {
      out.push(`${prefix}${key}:`)
      out.push(...renderValue(val, indent + (index === 0 && dash ? 4 : 2)))
    } else {
      out.push(`${prefix}${key}: ${scalar(val)}`)
    }
  }
  return out
}

/** Render a scalar leaf, quoting strings for YAML safety. */
function scalar(value: unknown): string {
  if (typeof value === 'string') return JSON.stringify(value)
  if (value === undefined) return 'null'
  return String(value)
}

/** One nested item collected while scanning a config block: its key and the raw line value. */
interface NestedItem {
  name?: string
  content?: string
  description?: string
}

/**
 * Best-effort parse of the rows this exporter writes. Rows it does not
 * recognize are ignored, so an external patch may carry other plugins.
 * @param text - a `cordis.patch.yml` document.
 * @returns the switchblade-owned rows found in it.
 */
export function parsePatch(text: string): SwitchbladePatch {
  let installedSkills: SkillDefinition[] = []
  let customCommands: CommandDefinition[] = []
  let defaultProfile: string | undefined

  // In-insert state machine: track the current row id and the current
  // config block we are scanning for `installedSkills`/`customCommands` arrays.
  const lines = text.split(/\r?\n/)
  let inInsert = false
  let currentRow: string | undefined
  let currentArray: 'installedSkills' | 'customCommands' | undefined
  let currentItem: NestedItem | undefined
  let pendingItems: NestedItem[] = []

  const flush = (): void => {
    if (currentItem !== undefined) pendingItems.push(currentItem)
    currentItem = undefined
    if (currentArray === 'installedSkills') {
      installedSkills = pendingItems.map((item) => ({
        name: item.name ?? '',
        content: item.content ?? '',
        description: item.description ?? '',
        invocation: { modelInvocable: true, userInvocable: true },
        provider: 'runtime',
        source: 'custom',
      }))
    } else if (currentArray === 'customCommands') {
      customCommands = pendingItems.map((item) => ({
        name: item.name ?? '',
        description: item.description ?? '',
        handler: () => ({ kind: 'success' as const, text: '' }),
      }))
    }
    pendingItems = []
  }

  for (const raw of lines) {
    const line = raw.trim()
    if (/^- insert:/.test(line)) {
      inInsert = true
      continue
    }
    if (!inInsert) continue

    const idMatch = /^- id:\s*(.+)$/.exec(line)
    if (idMatch !== null) {
      flush()
      currentArray = undefined
      currentRow = idMatch[1]
      continue
    }
    if (currentRow === undefined) continue

    if (line.startsWith('config:')) {
      flush()
      currentArray = undefined
      // Inline default (`config: { default: x }`) — the agent-presets row.
      const inline = /^config:\s*\{([^}]*)\}\s*$/.exec(raw.trim())
      if (inline !== null) {
        const body = inline[1] ?? ''
        const def = /default:\s*["']?([^"',}]+)["']?/.exec(body)
        if (def !== null) defaultProfile = def[1] ?? def[0]
      }
      continue
    }

    // Block-form `default: "graybeard"` line directly under an agent-presets
    // row's `config:` (no inline braces).
    if (currentRow === AGENT_PRESETS_ROW) {
      const def = /^default:\s*["']?([^"']+)["']?$/.exec(line)
      if (def !== null) defaultProfile = dequote(def[1] ?? '')
    }

    // Array markers under config.
    const arrayMatch = /^installedSkills:|^customCommands:/.exec(line)
    if (arrayMatch !== null) {
      flush()
      currentArray = arrayMatch[0].replace(':', '') as 'installedSkills' | 'customCommands'
      continue
    }

    // Item rows inside the array: `- name: "x"` or `- content: "..."`.
    if (currentArray !== undefined) {
      const itemStart = /^-\s+(\w+):\s*(.*)$/.exec(line)
      if (itemStart !== null) {
        flush()
        const key = itemStart[1]
        const rawValue = itemStart[2]
        if (key !== undefined && rawValue !== undefined) {
          currentItem = { [key]: dequote(rawValue) } as NestedItem
        }
        continue
      }
      const field = /^(\w+):\s*(.*)$/.exec(line)
      if (field !== null && currentItem !== undefined) {
        const key = field[1]
        const rawValue = field[2]
        if (key !== undefined && rawValue !== undefined) {
          if (key === 'name' || key === 'content' || key === 'description') {
            currentItem[key] = dequote(rawValue)
          }
        }
      }
    }
  }
  flush()
  return {
    installedSkills,
    customCommands,
    ...defaultProfile === undefined ? {} : { defaultProfile },
  }
}

/** Strip surrounding quotes from a scalar produced by this exporter. */
function dequote(raw: string): string {
  const value = raw.trim()
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).replaceAll('\\"', '"')
  }
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1)
  }
  return value
}
